todolist/blueprints/auth.py
from flask import render_template, flash, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, login_required, current_user

from todolist.forms import RegisterForm, LoginForm
from todolist.extension import db
from todolist.models import User

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        new_user = User(username=username)
        new_user.set_password(password)
        db.session.add(new_user)
        db.session.commit()
        flash('New user registered.', 'Success')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)

# login function
@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('todo.app'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data
        user = User.query.filter_by(username=username).first()
        # Judge if the user is none
        if user:
            # validate user
            if user.validate_password(password):
                login_user(user, remember)
                flash('Login success.', 'info')
                return redirect(url_for('todo.app'))
            flash('Invalid username or password.')
        else:
            flash('No account.', 'warning')
    return render_template('auth/login.html', form=form)

# log out current user.
@auth_bp.route('/logout')
def logout():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('home.index'))

todolist/blueprints/todo.py
from flask import flash, redirect, url_for, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from datetime import datetime, timedelta
from todolist.forms import TaskForm
from todolist.extension import db
from todolist.models import Task, Category, User, Comment

todo_bp = Blueprint('todo', __name__)


@todo_bp.route('/app', methods=['GET', 'POST'])
@login_required
def app():
    form = TaskForm()
    # Get the category of the current user
    form.category.choices = [(category.id, category.name)
                             for category in Category.query.with_parent(current_user).order_by(Category.name).all()]

    if form.validate_on_submit():
        # Create new task
        title = form.title.data
        content = form.content.data
        deadline = timedelta(days=form.deadline.data) + datetime.utcnow()
        category = Category.query.get(form.category.data)
        task = Task(title=title, content=content, category=category, user=current_user, deadline=deadline)
        db.session.add(task)
        db.session.commit()
        flash('Your task has been set!')
        return redirect(url_for('todo.app'))
    # Get the tasks and count data from database.
    tasks = Task.query.with_parent(current_user).order_by(Task.timestamp.desc()).all()
    all_count = Task.query.with_parent(current_user).count()
    finished_count = Task.query.with_parent(current_user).filter_by(is_finished=True).count()
    unfinished_count = Task.query.with_parent(current_user).filter_by(is_finished=False).count()
    return render_template('todo/app.html', form=form, tasks=tasks, all_count=all_count, finished_count=finished_count,
                           unfinished_count=unfinished_count)


@todo_bp.route('/category/<int:category_id>', methods=['GET', 'POST'])
@login_required
def show_category(category_id):
    form = TaskForm()
    # Get the category of the current user
    form.category.choices = [(category.id, category.name)
                             for category in Category.query.with_parent(current_user).order_by(Category.name).all()]
    if form.validate_on_submit():
        # Create new task
        title =form.title.data
        content = form.content.data
        deadline=timedelta(days=form.deadline.data) + datetime.utcnow()
        category = Category.query.get(form.category.data)
        task = Task(title=title, content=content, category=category, user=current_user, deadline=deadline)
        db.session.add(task)
        db.session.commit()
        flash('Your task has been set!')
        return redirect(url_for('todo.app'))
    # Get the tasks of current category and count data from database.
    current_category = Category.query.get_or_404(category_id)
    tasks = Task.query.with_parent(current_category).order_by(Task.timestamp.desc()).all()
    all_count = Task.query.with_parent(current_category).count()
    finished_count = Task.query.with_parent(current_category).filter_by(is_finished=True).count()
    unfinished_count = Task.query.with_parent(current_category).filter_by(is_finished=False).count()
    return render_template('todo/app.html', form=form, tasks=tasks, all_count=all_count, finished_count=finished_count,
                           unfinished_count=unfinished_count)

# Toggle the task
@todo_bp.route('/task/<int:task_id>/toggle', methods=['PATCH'])
@login_required
def toggle_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.user:
        return jsonify(message='Permission denied')
    task.is_finished = not task.is_finished
    db.session.commit()
    return jsonify(message='task toggled')


# Delete the task
@todo_bp.route('/task/<int:task_id>/delete', methods=['DELETE'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.user:
        return jsonify(message='Permission denied')
    db.session.delete(task)
    db.session.commit()
    return jsonify(message='task deleted')

# Create the comment of the task.
@todo_bp.route('/comment/<int:task_id>/new', methods=['POST'])
@login_required
def new_comment(task_id):
    data = request.get_json()
    task = Task.query.get_or_404(task_id)
    # Judge if the data is valid.
    if data is None or data['body'].strip() == '':
        return jsonify(message='Invalid comment.'), 400
    comment = Comment(content=data['body'], task=task)
    db.session.add(comment)
    db.session.commit()
    return jsonify(html=render_template('todo/_comment.html', comment=comment))

# Create new category
@todo_bp.route('/category/new', methods=['POST'])
@login_required
def new_category():
    data = request.get_json()

    if data is None or data['body'].strip() == '':
        return jsonify(message='Invalid category.'), 400
    category = Category(name=data['body'], user=current_user)
    db.session.add(category)
    try:
        db.session.commit()
    except:
        flash('Category already exist')
        db.session.rollback()  # rollback if category is repeated.
    return jsonify(html=render_template('todo/_category.html', category=category), message='+1')

todolist/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <title>Document</title>
</head>

<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Todolist</a>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav">
                    {{ render_nav_item('home.index','Home') }}
                    {{ render_nav_item('home.about','About') }}

                </ul>
            </div>
            <ul class="nav justify-content-end text-white">
                {% if current_user.is_authenticated %}
                    <a class="nav-item nav-link text-white" href="{{ url_for('auth.logout') }}">Log Out</a>
                {% else %}
                    <a class="nav-item nav-link text-white" href="{{ url_for('auth.login') }}">Log In</a>
                {% endif %}
            </ul>


        </div>
    </nav>
{% endblock nav %}
{% block title %}{% endblock %}
<header class="mb-5">
    <h1 class="text-center display-4">
        <small class="text-muted sub-title">Personal</small>
        <a class="text-success"><strong>To do list</strong></a>

    </h1>
</header>

{% for message in get_flashed_messages(with_categories=True) %}
    <div class="alert alert-{{ message[0] }}" role="alert">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message[1] }}
    </div>
{% endfor %}


{% block content %}{% endblock %}
<footer class="mt-5">
    <p class="text-center">
        <small> &copy; <a href="https://github.com/YangXiao-logic" title="Written by YangXiao">YangXiao</a> -
            <a href="https://github.com/YangXiao-logic/todolist" title="Fork me on GitHub">GitHub</a> -
            <a>Todolist</a>
        </small>
    </p>
</footer>

<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
{{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
<script src="{{ url_for('static', filename='js/script.js') }}" type="text/javascript"></script>
<script type="text/javascript">
    var new_category_url = "{{ url_for('todo.new_category') }}";
    var csrf_token = "{{ csrf_token() }}";
</script>
</body>


</html>