todolist/blueprints/todo.py
from flask import flash, redirect, url_for, render_template, Blueprint, jsonify, request
from flask_login import login_required, current_user
from datetime import datetime, timedelta
from todolist.forms import TaskForm
from todolist.extension import db
from todolist.models import Task, Category, User, Comment

todo_bp = Blueprint('todo', __name__)


@todo_bp.route('/app', methods=['GET', 'POST'])
@login_required
def app():
    form = TaskForm()
    # Get the category of the current user
    form.category.choices = [(category.id, category.name)
                             for category in Category.query.with_parent(current_user).order_by(Category.name).all()]

    if form.validate_on_submit():
        # Create new task
        title = form.title.data
        content = form.content.data
        deadline = timedelta(days=form.deadline.data) + datetime.utcnow()
        category = Category.query.get(form.category.data)
        task = Task(title=title, content=content, category=category, user=current_user, deadline=deadline)
        db.session.add(task)
        db.session.commit()
        flash('Your task has been set!')
        return redirect(url_for('todo.app'))
    # Get the tasks and count data from database.
    tasks = Task.query.with_parent(current_user).order_by(Task.timestamp.desc()).all()
    all_count = Task.query.with_parent(current_user).count()
    finished_count = Task.query.with_parent(current_user).filter_by(is_finished=True).count()
    unfinished_count = Task.query.with_parent(current_user).filter_by(is_finished=False).count()
    return render_template('todo/app.html', form=form, tasks=tasks, all_count=all_count, finished_count=finished_count,
                           unfinished_count=unfinished_count)


@todo_bp.route('/category/<int:category_id>', methods=['GET', 'POST'])
@login_required
def show_category(category_id):
    form = TaskForm()
    # Get the category of the current user
    form.category.choices = [(category.id, category.name)
                             for category in Category.query.with_parent(current_user).order_by(Category.name).all()]
    if form.validate_on_submit():
        # Create new task
        title =form.title.data
        content = form.content.data
        deadline=timedelta(days=form.deadline.data) + datetime.utcnow()
        category = Category.query.get(form.category.data)
        task = Task(title=title, content=content, category=category, user=current_user, deadline=deadline)
        db.session.add(task)
        db.session.commit()
        flash('Your task has been set!')
        return redirect(url_for('todo.app'))
    # Get the tasks of current category and count data from database.
    current_category = Category.query.get_or_404(category_id)
    tasks = Task.query.with_parent(current_category).order_by(Task.timestamp.desc()).all()
    all_count = Task.query.with_parent(current_category).count()
    finished_count = Task.query.with_parent(current_category).filter_by(is_finished=True).count()
    unfinished_count = Task.query.with_parent(current_category).filter_by(is_finished=False).count()
    return render_template('todo/app.html', form=form, tasks=tasks, all_count=all_count, finished_count=finished_count,
                           unfinished_count=unfinished_count)

# Toggle the task
@todo_bp.route('/task/<int:task_id>/toggle', methods=['PATCH'])
@login_required
def toggle_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.user:
        return jsonify(message='Permission denied')
    task.is_finished = not task.is_finished
    db.session.commit()
    return jsonify(message='task toggled')


# Delete the task
@todo_bp.route('/task/<int:task_id>/delete', methods=['DELETE'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    if current_user != task.user:
        return jsonify(message='Permission denied')
    db.session.delete(task)
    db.session.commit()
    return jsonify(message='task deleted')

# Create the comment of the task.
@todo_bp.route('/comment/<int:task_id>/new', methods=['POST'])
@login_required
def new_comment(task_id):
    data = request.get_json()
    task = Task.query.get_or_404(task_id)
    # Judge if the data is valid.
    if data is None or data['body'].strip() == '':
        return jsonify(message='Invalid comment.'), 400
    comment = Comment(content=data['body'], task=task)
    db.session.add(comment)
    db.session.commit()
    return jsonify(html=render_template('todo/_comment.html', comment=comment))

# Create new category
@todo_bp.route('/category/new', methods=['POST'])
@login_required
def new_category():
    data = request.get_json()

    if data is None or data['body'].strip() == '':
        return jsonify(message='Invalid category.'), 400
    category = Category(name=data['body'], user=current_user)
    db.session.add(category)
    try:
        db.session.commit()
    except:
        flash('Category already exist')
        db.session.rollback()  # rollback if category is repeated.
    return jsonify(html=render_template('todo/_category.html', category=category), message='+1')

todolist/templates/todo/_category.html
<li>
    <a href="{{ url_for('todo.show_category',category_id = category.id) }} " class="nav-link text-white
                {% if request.path==url_for('todo.show_category', category_id=category.id) %} active
                    {% endif %} "
            {% if request.path==url_for('todo.show_category', category_id=category.id) %} aria-current="true"
            {% endif %}>
        {{ category.name }}
    </a>
</li>

todolist/templates/todo/_comment.html
<figcaption class="blockquote-footer">
    {{ comment.content }}
</figcaption>

todolist/templates/todo/_inputTask.html
<form method="POST">
    {{ form.csrf_token }}
    <div class="row mb-3">
        <div class="col-2 form-group">
            {{ form.title.label(class='form-label') }}
            {{ form.title(class='form-control') }}
            {% for message in form.content.errors %}
                <div class="invalid-feedback">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="col-4 form-group">
            {{ form.content.label(class='form-label') }}
            {{ form.content(class='form-control') }}
            {% for message in form.content.errors %}
                <div class="invalid-feedback">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="col-2 form-group">
            {{ form.deadline.label(class='form-label') }}
            {{ form.deadline(class='form-select') }}
            {% for message in form.content.errors %}
                <div class="invalid-feedback">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="col-2 form-group">
            {{ form.category.label(class='form-label') }}
            {{ form.category(class='form-select') }}
            {% for message in form.content.errors %}
                <div class="invalid-feedback">
                    {{ message }}
                </div>
            {% endfor %}
        </div>

        <div class="col-2 form-group position-relative">
            {{ form.submit(class='position-absolute btn btn-secondary bottom-0') }}
        </div>
    </div>
</form>

todolist/templates/todo/_showTask.html
<table class="table">
    <thead>

    <input type="radio" class="btn-check" name="btnradio" id="unfinished-task" autocomplete="off">
    <label class="btn btn-outline-secondary position-relative" for="unfinished-task">Unfinished tasks
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary unfinished_count">
    {{ unfinished_count }}</span></label>
    <input type="radio" class="btn-check" name="btnradio" id="all-task" autocomplete="off" checked>
    <label class="btn btn-outline-secondary position-relative" for="all-task">All tasks
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary all_count">
    {{ all_count }}</span></label>
    <input type="radio" class="btn-check" name="btnradio" id="finished-task" autocomplete="off">
    <label class="btn btn-outline-secondary position-relative" for="finished-task">Finished tasks
        <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-secondary finished_count">
    {{ finished_count }}</span></label>

    </thead>
    <tbody class="tasks">

    {% for task in tasks %}
        {% include 'todo/_task.html' %}
    {% endfor %}
    </tbody>
</table>

todolist/templates/todo/_sidebar.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <span class="fs-4">Category</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{{ url_for('todo.app') }}" class="nav-link text-light
                    {% if request.path==url_for('todo.app') %} active
                    {% endif %} "
                    {% if request.path==url_for('todo.app') %} aria-current="true"
                    {% endif %}>
                All
            </a>
        </li>
        <div class="categories">
            {% for category in categories %}
                {% include 'todo/_category.html' %}
            {% endfor %}
        </div>
    </ul>
    <hr>
    <form method="POST">
        <div class="input-group mb-3">
            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
            <input id="category-input" data-href="{{ url_for('todo.new_category') }}" type="text"
                   placeholder="Create new category" autocomplete="off" autofocus required>
        </div>
    </form>
</div>

todolist/templates/todo/_task.html
{#<div class="task card mb-3" date-herf="{{ url_for('.edit_task', task_id=task.id) }}" data-id="{{ task.id }}"#}
{#     data-body="{{ task.body }}"#}
{#     data-is_finished={{ task.is_finished|tojson }}>#}
{#    <div class="row g-0">#}
{#        <div class="col-md-4">#}
{#            <img src="..." class="img-fluid rounded-start" alt="...">#}
{#        </div>#}
{#        <div class="col-md-8">#}
{#            <div class="card-body">#}
{#                <h5 class="card-title">{{ task.category.name }}</h5>#}
{#                <p class="card-text">{{ task.content }}</p>#}
{#                <a class="finished-btn btn btn-outline-secondary" data-href="{{ url_for('.toggle_task', task_id=task.id) }}"#}
{#                   role="button">{% if task.is_finished %}Finished{% else %}Unfinished{% endif %}</a>#}
{##}
{#                <p class="card-text"><small class="text-muted">{{ task.timestamp }}</small></p>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}


<div class="task card mb-3 position-relative" data-id="{{ task.id }}"
     data-is_finished={{ task.is_finished|tojson }}>
    <div class="card-header">
        {{ task.category.name }}

    </div>
    <div class="container">
        <div class="card-body row">
            <div class="col-8">
                <h3>{{ task.title }}</h3>
                <p class="card-text {% if task.is_finished %}finished-task{% else %}unfinished-task{% endif %}">{{ task.content }}</p>
                <div class="comments">
                    {% for comment in task.comments %}
                        {% include 'todo/_comment.html' %}
                    {% endfor %}
                </div>
                <a class="card-text"><small class="text-muted">{{ moment(task.timestamp).format('LL') }}</small></a>
                <div>Deadline: <a class="card-text"><small class="text-muted">{{ moment(task.deadline).format('LL') }}</small></a></div>
            </div>
            <div class="col-4">

                <a class="finished-btn btn btn-outline-secondary"
                   data-href="{{ url_for('.toggle_task', task_id=task.id) }}"
                   role="button">{% if task.is_finished %}Finished{% else %}Unfinished{% endif %}</a>
            </div>
            <div class="row">
                <div class="collapse" id="collapseExample{{ task.id }}">
                    <form method="POST">
                        <div class="input-group mb-3">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <input class="comment-input"
                                   data-href="{{ url_for('todo.new_comment',task_id=task.id) }}"
                                   type="text"
                                   placeholder="Create new comment" autocomplete="off" autofocus
                                   required>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
    <span class="position-absolute top-0 end-0">
        <a class="btn btn-secondary" data-bs-toggle="collapse" href="#collapseExample{{ task.id }}" role="button"
           aria-expanded="false"
           aria-controls="collapseExample{{ task.id }}">
            Comment
        </a>
        <button type="button" class="btn-close delete-btn" data-href="{{ url_for('.delete_task', task_id=task.id) }}"
                aria-label="Close"></button>
    </span>

</div>

todolist/templates/todo/show_category.html
{% extends 'todo/app.html' %}